[global]
daemonize = no
error_log = /run/stage/error.log
log_limit = 2048
[registry-stage]
listen = /run/stage/fpm.sock
listen.mode = 0660
pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 10s
pm.max_requests = 100
clear_env = yes
env[SILEX_REGISTRY_DATA] = /data
env[SILEX_GITHUB_CLIENT_ID] = $SILEX_GITHUB_CLIENT_ID
request_terminate_timeout = 25s
security.limit_extensions = .php
catch_workers_output = yes
