extension=pdo
extension=pdo_sqlite
extension=intl
extension=mbstring
extension=curl
memory_limit=128M
max_execution_time=20
display_errors=Off
log_errors=On
expose_php=Off
cgi.fix_pathinfo=0
allow_url_fopen=Off
allow_url_include=Off
enable_dl=Off
ffi.enable=Off
pcre.jit=0
disable_functions=exec,shell_exec,system,passthru,popen,proc_open,pcntl_exec,dl
sys_temp_dir=/tmp
